services:
  web:
    build: .
    env_file:
      - path: .env
        required: false
    environment:
      - WEB_PORT=${AI_PORT}
      - WEB_HOST=${AI_HOST}
      - PIPELINE_MODEL_NAME=${AI_PIPELINE_MODEL_NAME}
    ports:
      - "${AI_PORT}:${AI_PORT}"