
services:

  web:
    build: .
    env_file:
      - path: .env
        required: false
    environment:
      - WEB_HOST=${AI_HOST}                
      - WEB_PORT=${AI_PORT}
      - PIPELINE_MODEL_NAME=${AI_PIPELINE_MODEL_NAME}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_GRPC_PORT=${QDRANT_GRPC_PORT}
    ports:
      - "${AI_PORT}:${AI_PORT}"
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - greener_net

  qdrant:
    build:
      context: .
      dockerfile: qdrant.dockerfile
      args:
        QDRANT_VERSION: ${QDRANT_VERSION}
    env_file:
      - path: .env
        required: false
    environment:
      - QDRANT__SERVICE__HOST=${QDRANT_HOST}
      - QDRANT__SERVICE__HTTP_PORT=${QDRANT_PORT}
      - QDRANT__SERVICE__GRPC_PORT=${QDRANT_GRPC_PORT}
      - QDRANT__LOG_LEVEL=${QDRANT_LOG_LEVEL}
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "http://localhost:${QDRANT_PORT}/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - greener_net

volumes:
  qdrant_storage:

networks:
  greener_net:
    driver: bridge
