
services:

  web:
    build: .
    env_file:
      - path: .env
        required: false
    environment:
      - WEB_HOST=${AI_HOST}                
      - WEB_PORT=${AI_PORT}
      - PIPELINE_MODEL_NAME=${AI_PIPELINE_MODEL_NAME}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_GRPC_PORT=${QDRANT_GRPC_PORT}
    ports:
      - "${AI_PORT}:${AI_PORT}"
    volumes:
      - ./images:/greener/images
      - ./backup_images:/greener/backup_images
      - ./data:/greener/data

  qdrant:
    build:
      context: .
      dockerfile: qdrant.dockerfile
      args:
        QDRANT_VERSION: ${QDRANT_VERSION}
    env_file:
      - path: .env
        required: false
    environment:
      - QDRANT__SERVICE__HOST=${QDRANT_HOST}
      - QDRANT__SERVICE__HTTP_PORT=${QDRANT_PORT}
      - QDRANT__SERVICE__GRPC_PORT=${QDRANT_GRPC_PORT}
      - QDRANT__LOG_LEVEL=${QDRANT_LOG_LEVEL}
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
  images:
  backup_images:
  data: